# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23cfe2261e144bd749e8d46dbe3beb5ea51b26b78e1dd5eb33baf185a3d6d836ef5d123c1a694eb39d8716540485da39b032fe2ee867489250cb7c726e323aa

test:
  secret_key_base: b619f237508e9b4bd89c96d32e3d7e67db9944a134fc9399bcb94d6129da1aea25cef63ba55dd62bc3de07176f80c00a519640a5708227e46f6b128e622fbef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
